#!/usr/bin/env python3
"""Generate the namespaced tuned summation stack without touching baseline modules."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "lean" / "Erdos327" / "Analytic"
TARGET = ROOT / "lean" / "Erdos327" / "Tuned.lean"
MODULES = (
    "TailInstantiation",
    "SourceScheduledSummation",
    "SourceSupportedReduction",
    "SourceMainSummation",
    "SourceBoundarySummation",
    "SourceTerminalSummation",
    "SourceErrorCoupling",
    "SourceFinalSummation",
    "ScheduledReduction",
    "MixedScheduledSummation",
    "MixedMainSummation",
    "MixedTerminalSummation",
    "MixedBoundarySummation",
    "MixedBudgetSummation",
    "MixedFinalSummation",
)


def body(name: str) -> str:
    text = (SOURCE / f"{name}.lean").read_text()
    marker = "namespace Erdos327.Analytic\n"
    start = text.index(marker) + len(marker)
    end = text.rindex("end Erdos327.Analytic")
    return text[start:end].strip()


def main() -> None:
    chunks = [body(name) for name in MODULES]
    chunks[0] = chunks[0].replace(
        "def sourceAnatomySlope : ℝ := 1.000001\n"
        "def sourceTailBase : ℝ := 1.000001",
        "def sourceAnatomySlope : ℝ := 1.0003\n"
        "def sourceTailBase : ℝ := 1.0003",
    ).replace(
        "(x := (1 / 1000000 : ℝ))",
        "(x := (3 / 10000 : ℝ))",
    )
    tuned_source_exponent = """

/-- Tuned source exponent certificate, isolated from the baseline parameter. -/
theorem source_exponent_lt_three_halves :
    sourceAnatomySlope * Real.log 4 < 3 / 2 := by
  rw [Real.log_four_eq]
  norm_num [sourceAnatomySlope] at ⊢
  nlinarith [Real.log_two_lt_d9]
""".strip()
    insertion = chunks[0].index("theorem sourceAnatomySlope_nonneg")
    chunks[0] = chunks[0][:insertion] + tuned_source_exponent + "\n\n" + chunks[0][insertion:]
    chunks = [chunk.replace(
        "Erdos327.source_exponent_lt_three_halves",
        "source_exponent_lt_three_halves",
    ).replace("1.000001", "1.0003") for chunk in chunks]
    old_quadratic = """  have hM2 :
      sourceAnatomySlope * log 4 ≤ 2 := by
    unfold sourceAnatomySlope
    linarith [source_exponent_lt_three_halves]"""
    new_quadratic = """  have hM2 :
      sourceAnatomySlope * log 4 ≤ 2 :=
    source_exponent_lt_three_halves.le.trans (by norm_num)"""
    chunks = [chunk.replace(old_quadratic, new_quadratic) for chunk in chunks]
    old_cross = """  simpa [mixedCanonicalCrossExponent, sourceAnatomySlope,
    oddAnatomySlope, mixedSourceWeightBase, mixedOddWeightBase] using
    Erdos327.cross_exponent_lt_neg_one"""
    new_cross = """  unfold mixedCanonicalCrossExponent sourceAnatomySlope
    oddAnatomySlope mixedSourceWeightBase mixedOddWeightBase
  norm_num at ⊢
  nlinarith [Erdos327.log_qb_upper, Erdos327.log_qo_upper]"""
    chunks = [chunk.replace(old_cross, new_cross) for chunk in chunks]

    header = """import Erdos327

/-! Generated by `audit/generate_tuned_stack.py` from the baseline summation
modules.  Only the source slope/base and their two numerical certificates are
changed; all declarations live in a separate namespace. -/

namespace Erdos327.Tuned.Analytic

open Erdos327.Analytic
"""
    footer = "\n\nend Erdos327.Tuned.Analytic\n"
    TARGET.write_text(header + "\n\n".join(chunks) + footer)
    print(f"wrote {TARGET} ({TARGET.read_text().count(chr(10))} lines)")


if __name__ == "__main__":
    main()
